apiVersion: v1
kind: Pod
metadata:
  name: prometheus-pod
  labels:
    skillshare: prometheus
spec:
  volumes:
  - name: prometheus-config-volume
    configMap:
      name: prometheus-config
  - name: prometheus-volume
    persistentVolumeClaim:
      claimName: prometheus-storage
  containers:
  - name: prometheus
    image: prom/prometheus
    ports:
    - containerPort: 9090
    volumeMounts:
    - name: prometheus-config-volume
      mountPath: /etc/prometheus/
    volumeMounts:
    - name: prometheus-volume
      mountPath: /data/prometheus/
