apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
spec:
  storageClassName: prometheus-storage
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /mnt/c/Users/rafs9/Documents/Aula/PersistentVolume/prometheus
