apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
spec:
  storageClassName: prometheus-storage
  resources:
    requests:
      storage: 200Mi
  accessModes:
  - ReadWriteMany
