apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-deployment
  labels:
    skillshare: application
spec:
  replicas: 4
  selector:
    matchLabels:
      skillshare: application
  template:
    metadata:
      name: application
      labels:
        skillshare: application
    spec:
      containers:
      - name: application
        image: rafael097/infnet-devops-application:latest
        livenessProbe:
          httpGet:
            path: /livenessProbe/isAlive
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 60
        env:
        - name: DATABASE_URL
          value: "10.109.203.66"
